# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/crackcomm/nsqueue"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/context"

[[constraint]]
  branch = "master"
  name = "github.com/karlentwistle/route53"

[[constraint]]
  name = "github.com/rs/cors"
  version = "v.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/virtengine/go-radosgw"

[[constraint]]
  branch = "master"
  name = "github.com/virtengine/go-rancher"

[[constraint]]
  branch = "master"
  name = "github.com/virtengine/libgo"

[[constraint]]
  branch = "master"
  name = "github.com/virtengine/opennebula-go"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"

[[constraint]]
  branch = "(default)"
  name = "launchpad.net/gnuflag"

[prune]
  go-tests = true
  unused-packages = true
